codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "60...90"

  status:
    project:
      default:
        target: 70%
        threshold: 2%
        if_ci_failed: error

    patch:
      default:
        target: 80%
        threshold: 0%
        if_ci_failed: error

comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: true
