"""MkDocs documentation generation scripts.

This package contains scripts that run during mkdocs build:
- gen_diagrams.py: Auto-generates class diagrams using pyreverse

API reference is auto-generated by mkdocs-api-autonav plugin.
"""
